Repository masters2023-project-03-second-hand/second-hand-max-fe, pull requests merged in 2023-09, with the labels that each got.

#11 feat: ModalSheet 컴포넌트 및 LocationModal (#10)
  src/assets/icons/circle-x-filled.svg
  src/components/ModalSheet/LocationModal/Header.tsx
  src/components/ModalSheet/LocationModal/index.tsx
  src/components/ModalSheet/index.tsx
  src/components/SecondHand.tsx
  src/contexts/AppContext.tsx
Labels: feat

#12 내 계정 페이지 UI, 기능 구현
  .gitignore
  package.json
  public/mockServiceWorker.js
  src/apis/fetchApi.ts
  src/components/Button.tsx
  src/components/ProfileImageButton.tsx
  src/components/TopBar.tsx
  src/constants/PATH.ts
  src/hooks/useOAuth.ts
  src/main.tsx
  src/mocks/data/sign.ts
  src/mocks/handlers.ts
  src/mocks/worker.ts
  src/pages/MyAccount/OAuthLoadingPage.tsx
  src/pages/MyAccount/Profile.tsx
  src/pages/MyAccount/SignInForm.tsx
  src/pages/MyAccount/SignUpForm.tsx
  src/routes.tsx
Labels: feat

#19 회원가입, 로그인 여러번 요청하던 오류 수정
  src/hooks/useOAuth.ts
Labels: fix

#20 3주차 중간 머지
  package-lock.json
  package.json
  src/App.tsx
  src/apis/fetchApi.ts
  src/apis/types.ts
  src/components/Field/FieldCaption.tsx
  src/components/Field/index.ts
  src/components/ProfileImageButton.tsx
  src/components/SecondHand.tsx
  src/constants/LOCAL_STORAGE_KEY.ts
  src/hooks/useOAuth.ts
  src/pages/MyAccount/Profile.tsx
  src/pages/MyAccount/SignInForm.tsx
  src/pages/MyAccount/SignUpForm.tsx
  src/pages/MyAccount/index.tsx
  src/types/Product.ts
Labels: feat

#21 zustand 도입 user, token 전역 상태로 관리
  package-lock.json
  package.json
  src/apis/api.ts
  src/apis/fetchData.ts
  src/apis/types.ts
  src/constants/BASE_URL.ts
  src/hooks/useOAuth.ts
  src/pages/MyAccount/Profile.tsx
  src/pages/MyAccount/index.tsx
  src/stores/useTokenStore.ts
  src/stores/useUserStore.ts
Labels: feat

#24 3주차 리뷰 반영 및 리팩토링
  src/apis/auth/index.ts
  src/apis/auth/types.ts
  src/apis/fetchData.ts
  src/apis/region/index.ts
  src/assets/default-profile-image.png
  src/components/ProductList/ListItem.tsx
  src/components/ProfileImageUploader.tsx
  src/components/Tabs/TabList.tsx
  src/constants/LOCAL_STORAGE_KEY.ts
  src/hooks/useImageFileHandler.ts
  src/hooks/useOAuth.ts
  src/pages/MyAccount/Profile.tsx
  src/pages/MyAccount/SignUpForm.tsx
  src/pages/MyAccount/index.tsx
  src/stores/useUserAuthStore.ts
  src/stores/useUserStore.ts
  src/types/index.ts
Labels: refactor

#26 내 계정 기능 구현
  src/App.tsx
  src/apis/region/index.ts
  src/components/InfiniteScrollTrigger.tsx
  src/components/Modal/ModalSheet.tsx
  src/components/Modal/RegionSettingModal/AddRegionModal/RegionList.tsx
  src/components/Modal/RegionSettingModal/AddRegionModal/index.tsx
  src/constants/QUERY_KEY.ts
  src/hooks/queries/useRegionQuery.ts
Labels: feat

#28 4주차 코드리뷰 반영
  package-lock.json
  package.json
  src/apis/auth/index.ts
  src/apis/fetchData.ts
  src/components/Dropdown/DropdownContainer.tsx
  src/components/Dropdown/DropdownContext.tsx
  src/components/Dropdown/DropdownIndicator.tsx
  src/components/Dropdown/DropdownMenus.tsx
  src/components/Dropdown/useDropdownContext.ts
  src/components/SecondHand.tsx
  src/constants/ERROR_MESSAGE.ts
  src/hooks/useOAuth.ts
  src/pages/Home/Title.tsx
  src/stores/useUserStore.ts
Labels: refactor

#32 5주차 중간머지
  src/apis/auth/index.ts
  src/apis/category/index.ts
  src/apis/category/types.ts
  src/apis/fetchData.ts
  src/apis/product/index.ts
  src/apis/product/types.ts
  src/apis/region/types.ts
  src/components/BackButton.tsx
  src/components/Fab.tsx
  src/components/Modal/CategoryListModal/CategoryList.tsx
  src/components/Modal/CategoryListModal/CategoryListModalHeader.tsx
  src/components/Modal/CategoryListModal/index.tsx
  src/components/Modal/CategoryModal/CategoryList.tsx
  src/components/Modal/CategoryModal/Header.tsx
  src/components/Modal/CategoryModal/index.tsx
  src/components/Modal/FullScreenModalSheet.tsx
  src/components/Modal/NewProductModal/EditBar.tsx
  src/components/Modal/NewProductModal/Main/PictureList/PictureItem.tsx
  src/components/Modal/NewProductModal/Main/PictureList/index.tsx
  src/components/Modal/NewProductModal/Main/Title.tsx
  src/components/Modal/NewProductModal/Main/index.tsx
  src/components/Modal/NewProductModal/index.tsx
  src/components/Modal/RegionSettingModal/AddRegionModal/index.tsx
  src/components/Modal/RegionSettingModal/index.tsx
  src/components/Modal/index.tsx
  src/components/ModalSheet/CategoryForm/CategoryList.tsx
  src/components/ModalSheet/CategoryForm/Header.tsx
  src/components/ModalSheet/CategoryForm/index.tsx
  src/components/ProductList/ListItem.tsx
  src/components/ProductList/index.tsx
  src/components/SecondHand.tsx
  src/components/Tag.tsx
  src/components/TopBar.tsx
  src/constants/ACCEPTED_EXTENSIONS.ts
  src/constants/BASE_URL.ts
  src/constants/ENV_VARIABLES.ts
  src/constants/PATH.ts
  src/constants/QUERY_KEY.ts
  src/hooks/queries/useCategoryQuery.ts
  src/hooks/queries/useProductQuery.ts
  src/hooks/useDebounce.ts
  src/hooks/useDraggable.ts
  src/hooks/useImageFileReader.ts
  src/hooks/useOAuth.ts
  src/pages/Home/Title.tsx
  src/pages/Home/TopBar/CategoryButton.tsx
  src/pages/Home/TopBar/RegionDropdown.tsx
  src/pages/Home/TopBar/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyAccount/SignUpForm/index.tsx
  src/routes.tsx
  src/stores/useModalStore.ts
  src/stores/useUserStore.ts
  src/types/category.ts
  src/types/index.ts
  src/types/product.ts
  src/types/region.ts
Labels: feat
